name: build and publish
on: [push]
#  push:
#    branches:
#      - main
jobs:
  publish-binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Build binary
      run: |
        go version
        go build .

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: current-release
        release_name: main
        body: Release for deployment into ipfs-check-backend.ipfs.io
        draft: false
        prerelease: false

    - name: Upload binary to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ipfs-check
        asset_name: ipfs-check
        asset_content_type: application/octet-stream
